---
name: Run pytest

permissions:
  checks: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        required: true
        type: string
      pr-head-sha:
        required: true
        type: string

jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head }}
      - name: install-poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: poetry-install
        run: poetry install
      - name: pytest
        env:
          COLUMNS: 500
          FORCE_COLOR: false
        run: rye run pytest --junit-xml=pytest.xml
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: pytest.xml
          commit: ${{ inputs.pr-head-sha }}
