---
name: Move PR

permissions:
  pull-requests: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      pr-number:
        description: The PR number to move
        type: number
        required: true
      base:
        description: The base branch to move the PR to
        type: string
        required: true

jobs:
  move-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: move-pr
        env:
          GH_TOKEN: ${{ github.token }}
          INPUTS_BASE: ${{ inputs.base }}
          COMMENT: |
            # 🤖 \*bleep bloop\*

            This PR will be moved to the ${{ inputs.base }} branch.

        run: |
          gh pr comment ${{ inputs.pr-number }} --body "${COMMENT}"
          gh pr edit ${{ inputs.pr-number }} --base "${INPUTS_BASE}"
