---
name: Publish Release

permissions:
  contents: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      changes:
        description: "The changelog for the release"
        required: true
        type: string

      version:
        description: "The version to bump to"
        type: string
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: write-changelog
        shell: python
        env:
          CHANGELOG: ${{ inputs.changes }}
        run: |
          import os
          with open('CHANGELOG.md', 'w') as f:
            f.write(os.environ['CHANGELOG'])
      - name: publish-release
        env:
          GH_TOKEN: ${{ github.token }}
          INPUTS_VERSION: ${{ inputs.version }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          gh release create "${INPUTS_VERSION}" \
            --notes-file CHANGELOG.md \
            --title "${INPUTS_VERSION}"
          git tag -f 'latest'
          git push origin 'latest' --force
