---
name: Synchronize pyproject.toml and requirements.lock

permissions:
  contents: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        description: The branch to checkout
        type: string
        required: true
      version:
        description: The version to set in pyproject.toml
        type: string
        required: true

jobs:
  pyproject:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache
        with:
          key: ${{ hashFiles('pyproject.toml', 'uv.lock', 'requirements.lock', 'requirements-dev.lock') }}-${{ inputs.version }}
          path: |
            pyproject.toml
            uv.lock
            requirements.lock
            requirements-dev.lock
      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b
        if: steps.cache.outputs.cache-hit != 'true'
      - name: version
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          INPUTS_VERSION: ${{ inputs.version }}
        run: uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version "${INPUTS_VERSION}"
      - name: lock
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          uv lock
          uv export --no-dev --no-hashes > requirements.lock
          uv export --no-hashes > requirements-dev.lock
      - name: git-commit
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          INPUTS_VERSION: ${{ inputs.version }}
        run: |
          git config --global user.email ""
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git diff --exit-code || {
            git commit -am "chore[bump]: ${INPUTS_VERSION}"
            git push
          }
      - uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          key: ${{ hashFiles('pyproject.toml', 'uv.lock', 'requirements.lock', 'requirements-dev.lock') }}-${{ inputs.version }}
          path: |
            pyproject.toml
            uv.lock
            requirements.lock
            requirements-dev.lock

