---
name: Generate Changelog

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        description: The HEAD to get changes from
        required: true
        type: string
      base:
        description: The base tag to compare against
        required: true
        type: string
    outputs:
      changes:
        description: "The changes between the two tags"
        value: "${{ jobs.changelog.outputs.changes }}"

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changes: "${{ steps.changelog.outputs.changes }}"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: requarks/changelog-action@b78a3354a01f4a1affb484b9264b506a815c46b1 # v1.10.3
        id: changelog
        with:
          token: ${{ github.token }}
          fromTag: ${{ inputs.head }}
          toTag: ${{ inputs.base }}
          writeToFile: false
          excludeScopes: "bump"
