# Create or update a release PR for merging dev -> main
---
name: Push to dev

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}

jobs:
  semver:
    name: Calculate next version
    uses: ./.github/workflows/def_semver.yml
    with:
      head: dev

  changelog:
    name: Generate changelog
    uses: ./.github/workflows/def_changelog.yml
    with:
      head: dev
      base: main

  pyproject:
    name: Synchonize pyproject
    needs: [semver]
    uses: ./.github/workflows/def_sync_pyproject.yml
    permissions:
      contents: write
    with:
      head: dev
      version: ${{ needs.semver.outputs.next }}-dev+${{ needs.semver.outputs.shorthash }}

  release-pr:
    name: Create/update release PR
    needs: [semver, changelog, pyproject]
    uses: ./.github/workflows/def_release-pr.yml
    permissions:
      pull-requests: write
    with:
      head: dev
      base: main
      version: ${{ needs.semver.outputs.next }}
      changes: ${{ needs.changelog.outputs.changes }}

  pytest:
    name: Run tests
    needs: [pyproject, release-pr]
    uses: ./.github/workflows/def_pytest.yml
    permissions:
      checks: write
      pull-requests: write
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}-pytest
    with:
      head: dev
      pr-head-sha: '${{ needs.release-pr.outputs.pr-head-sha }}'
